language: node_js
node_js:
  - '10'

# Travis-CI Caching
cache:
  directories:
    - node_modules

# S: Build Lifecycle
install:
  - yarn install

# 无其他依赖项所以执行npm run build 构建就行了
script:
  - npm run test:unit

after_success:
  - npm run coverage
